package repositories

const GetListaPendencia string = ` 
									select   top 1
											case when HISTLISE_FOR.EMPRESA_RECNO =  '5' tHEN '05.552.102/0005-67' ELSE '05.552.102/0001-33' END Cnpj,
											case when HISTLISE_FOR.EMPRESA_RECNO = '5' then	'3' ELSE '2' END AS LocalEstoque, 
										HISTLISE_FOR.DTENT DATA_MOV,  GRADE.COD_GRADE, GRADE.TAMANHO_GRADE, 
										'80751' as ITEM,  GRADE.DESCRICAO DESCRICAO, DESCRICAO, ESTOQUE.CUSTO_MEDIO,  SUM(1) QTDEMOV
										from HISTLISE_FOR 
										inner join HISTLISE H on H.RECNO_NOTA = HISTLISE_FOR.R_E_C_N_O_
										inner join ESTOQUE ON ESTOQUE.CODIGO = H.ITEM
											INNER JOIN GRUPOE ON GRUPOE.GRUPO = ESTOQUE.FAMILIA 
											inner join CST_GRADE_ESTOQUE GRADE ON GRADE.CODIGO_EPI = ESTOQUE.CODIGO or GRADE.CODIGO_EPI = '80751'
										WHERE HISTLISE_FOR.EFETUADOENTR = 'S' 
											AND CST_INTEGRARRSDATA = 'S'
											AND CONVERT(VARCHAR,HISTLISE_FOR.DTENT,112) = CONVERT(VARCHAR,GETDATE()-120,112)
										--	AND HISTLISE_FOR.DTENT NOT IN ( select DATA_MOV from CST_LANCAMENTOS_RSDATA WHERE CST_LANCAMENTOS_RSDATA.ITEM = H.ITEM and 
										--	case when HISTLISE_FOR.EMPRESA_RECNO =  '5' tHEN '05.552.102/0005-67' ELSE '05.552.102/0001-33' END = CST_LANCAMENTOS_RSDATA.CNPJ
										--	and  RETORNO_DETALHADO = 'Movimento inserido e estoque atualizado com sucesso!'
										--	)
										--  and ESTOQUE.CODIGO IN ('55386')
										--	and HISTLISE_FOR.EMPRESA_RECNO = 1
										GROUP BY HISTLISE_FOR.DTENT,  GRADE.DESCRICAO, H.ITEM, H.DESCRI, ESTOQUE.CUSTO_MEDIO , HISTLISE_FOR.EMPRESA_RECNO, GRADE.COD_GRADE, GRADE.TAMANHO_GRADE
									order BY HISTLISE_FOR.EMPRESA_RECNO, HISTLISE_FOR.DTENT DESC
								`

const GetListaPendencia_cargaini = ` select  HISTLISE_FOR.DTENT DATA_MOV, H.ITEM, H.DESCRI DESCRICAO, ESTOQUE.CUSTO_MEDIO, ESTOQUE.SALDOREAL QTDEMOV
											from HISTLISE_FOR 
											inner join HISTLISE H on H.RECNO_NOTA = HISTLISE_FOR.R_E_C_N_O_
											inner join ESTOQUE ON ESTOQUE.CODIGO = H.ITEM
											INNER JOIN GRUPOE ON GRUPOE.GRUPO = ESTOQUE.FAMILIA 
  									 WHERE HISTLISE_FOR.EFETUADOENTR = 'S' 
												AND CST_INTEGRARRSDATA = 'S'
												AND ESTOQUE.SALDOREAL > 0
												AND ESTOQUE.CODIGO <> '000038'
												AND H.R_E_C_N_O_ = (SELECT MAX(X.R_E_C_N_O_) FROM HISTLISE X WHERE X.ITEM = H.ITEM)
												AND GRUPOE.DESGRUPO IN ('AVENTAL', 'CALÇADOS', 'CAPACETE', 'MANGOTE', 'MASCARA', 'OCULOS', 'PERNEIRA',
												'PROTETOR AUDITIVO', 'UNIFORME', 'CREME', 'EPIS PARA TRABALHO EM ALTURA', 'CAPA PARA CHUVA')
									`

const GetListaItens string = `
								 select  isnull(grade.COD_GRADE, ESTOQUE.CODIGO) AS ITEM, ESTOQUE.DESCRI DESCRICAO, ESTOQUE.CUSTO_MEDIO, GRADE.TAMANHO_GRADE
								from ESTOQUE 
								left join CST_GRADE_ESTOQUE GRADE ON GRADE.CODIGO_EPI = ESTOQUE.CODIGO  
								left JOIN GRUPOE ON GRUPOE.GRUPO = ESTOQUE.FAMILIA 
									WHERE  CST_INTEGRARRSDATA = 'S'   
									  and codigo = '80751'
								ORDER BY CODIGO
							`

const GetItemGrade string = `
								 select  isnull(grade.COD_GRADE, ESTOQUE.CODIGO) AS ITEM, ESTOQUE.DESCRI DESCRICAO, ESTOQUE.CUSTO_MEDIO, GRADE.TAMANHO_GRADE
								from ESTOQUE 
								left join CST_GRADE_ESTOQUE GRADE ON GRADE.CODIGO_EPI = ESTOQUE.CODIGO  
								left JOIN GRUPOE ON GRUPOE.GRUPO = ESTOQUE.FAMILIA 
									WHERE  CST_INTEGRARRSDATA = 'S'   
									  and grade.COD_GRADE = ?
									  and GRADE.TAMANHO_GRADE = ?
								ORDER BY CODIGO
							`
